// import Header from '@/app/components/ui/Header/index';
import React from 'react';
import type { Metadata } from 'next';

// import Toastify from '@/app/components/ui/toastify/sonner/toastify';
// import Image from 'next/image';

export const metadata: Metadata = {
    title: ' Test',
    description: 'Generated by kai',
};
const TestPage = () => {
    return (
        <div>
            {/* <Header name={'qwe'}></Header> */}
            <div>TestPage</div>
            {/* <Image src='/next.svg' width={100} height={100} alt='123'></Image> */}
        </div>
    );
};

export default TestPage;
